- type: entity
  parent: BaseItem
  id: BaseBoardEntity # Board item
  name: 板子
  abstract: true
  description: 一块空白的板子。
  components:
    - type: TabletopGame
      size: 256, 256
      setup:
        !type:TabletopEmptySetup
        boardPrototype: Crowbar
    - type: Tag
      tags:
        - TabletopBoard

- type: entity
  id: BaseTabletopPiece # Board piece
  parent: BaseItem
  abstract: true
  components:
  - type: TabletopDraggable
  - type: Sprite
    noRot: true
  - type: Appearance
  - type: Tag
    tags:
      - TabletopPiece

- type: entity
  id: BaseBoardTabletop
  name: 踢脚线
  abstract: true
  categories: [ HideSpawnMenu ]
  components:
  - type: Tag
    tags:
      - TabletopBoard
  - type: Sprite
    noRot: false
    drawdepth: FloorTiles
